---
sealed-secrets:

  commandArgs:
    - --key-renew-period
    - "0"

  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 50m
      memory: 128Mi

  controller:
    # controller.create: `true` if Sealed Secrets controller should be created
    create: true

  # namespace: Namespace to deploy the controller.
  namespace: "sealed-secrets"

  # secretName: The name of the TLS secret containing the key used to encrypt secrets
  secretName: sealed-secrets-key

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      certmanager.k8s.io/cluster-issuer: ca-issuer

    path: /v1/cert.pem
    hosts:
      - sealed-secrets.dev.local
    tls:
      - secretName: sealed-secrets-crt
        hosts:
          - sealed-secrets.dev.local
