apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: redis
  namespace: argocd-system
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: Namespace
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://charts.bitnami.com/bitnami
status: {}
