apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd-system
spec:
  destination:
    namespace: keycloak
    server: https://kubernetes.default.svc
  project: tools
  source:
    chart: keycloak
    helm:
      parameters:
      - name: auth.adminPassword
        value: pleasechangeme
      - name: auth.adminUser
        value: admin
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 5.1.6
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
