{{- if .Values.photoprism -}}
{{- if .Values.photoprism.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: photoprism
spec:
  destination:
    name: 'photoprism'
    namespace: photoprism
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://p80n.github.io/photoprism-helm/
    targetRevision: 1.3.1
    chart: photoprism
  sources: []
  project: apps
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true

{{- end }}
{{- end }}
