{{- if .Values.apps -}}
{{- if .Values.apps.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd-system
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: Namespace
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://charts.bitnami.com/bitnami
  - https://github.com/ylascombe/local-k8s-terraform
  - https://stefanprodan.github.io/podinfo
  - https://prometheus-community.github.io/helm-charts
  - https://p80n.github.io/photoprism-helm/
status: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-{{ .Values.cluster_name }}
  namespace: argocd-system
spec:
  destination:
    namespace: argocd-system
    server: https://kubernetes.default.svc
  project: apps
  source:
    helm:
      parameters:
      - name: server
        value: https://kubernetes.default.svc
      valueFiles:
      - dev.values.yaml
    path: helm/infra/app-of-apps
    repoURL: https://github.com/ylascombe/local-k8s-terraform
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
 
{{- end }}
{{- end }}
