{{- if .Values.sealedSecrets -}}
{{- if .Values.sealedSecrets.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd-system
spec:
  destination:
    namespace: sealed-secrets
    server: {{ .Values.server }}
  project: tools
  source:
    path: helm/infra/sealed-secrets
    repoURL: https://github.com/ylascombe/local-k8s-terraform
    targetRevision: main
    helm:
      valueFiles:
        - {{ .Values.sealedSecrets.valueFile }}
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true

{{- end }}
{{- end }}
