{{- if eq .Values.issuer "letsencrypt" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  acme:
    email: donotexist@gmail.com
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
{{- end }}
{{- if eq .Values.issuer "buypass" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  acme:
    email: donotexist@gmail.com
    preferredChain: ""
    privateKeySecretRef:
      name: buypass-issuer-account-key
    server: https://api.buypass.com/acme/directory
    solvers:
      - http01:
          ingress:
            class: nginx
{{- end }}
